### ISSUE TITLE
Membership Tool

### ISSUE THREAD

**Issue by kevinschoonover** [sigdotcom/mstacm.org#48]
Update tool located at https://github.com/sigdotcom/oasis/blob/membership_welch/src/screens/Tools/Membership/index.tsx to using latest technology stack

**Comment by ClayMav** [comment]
# Updates:
### The front end of this tool should have the following:
- [ ] Search for specific user
- [ ] clear all ACM shirt information button (prompt after pressing to confirm, should only be pressed if shirt have just been ordered and arrived)
- [ ] A list of users and for each user:
  - [ ] An edit button which should present the user with:
    - [ ] the ability to change their current membership start date and length (semester or year)
    - [ ] the ability to select that the user has picked up their ACM shirt
    - [ ] the ability to delete the user completely (on selecting this, prompt for confirmation)
  - [ ] membership start date and expiry date
  - [ ] registration date for the website

### The back end will need:
- [ ] per-user shirt picked up information
- [ ] a mutation to delete a user completely
- [ ] a query for getting all users
