### ISSUE TITLE
Update look of ACM Membership Payment

### ISSUE THREAD

**Issue by kevinschoonover** [sigdotcom/mstacm.org#92]
Paying for ACM Membership does not look very secure to users due to its design. We should update the design to make it look nicer.

![Screenshot_2019-09-07 S T ACM Home](https://user-images.githubusercontent.com/17842707/64478497-e29c1b80-d16e-11e9-92aa-e17854d6e359.png)

**Comment by ClayMav** [comment]
- [ ] Add field for name
- [ ] Split up the current fields into separate boxes
- [ ] Review button
- [ ] Review screen (how much you are paying, name, are you sure button)
- [ ] Pressing yes on the review screen loads until complete
- [ ] Once membership has been processed, rerender page behind modal to reflect
